### ISSUE TITLE
Missing user friendly message when request contains empty cfInstanceId

### ISSUE THREAD

**Issue by gberche-orange** [spring-cloud/spring-cloud-cloudfoundry-service-broker#53]
As a user, if I make the mistake of adding a trailing slash when registering my broker

```
cf create-service-broker mybroker user secret https://mybroker.site.org/
```

then surprisingly the spring-cloud-cloudfoundry-service-broker will reject requests sent by the CF cloudcontroller of the form ```https://mybroker.site.org//v2/service_instances/ef1fcb74-55ea-407a-bf79-7c09d8bdd949/last_operation?plan_id=aplan&service_id=aserviceid``` with the following exception:

```
2017-11-22T11:37:47.09+0100 [APP/PROC/WEB/0] OUT org.springframework.web.bind.MissingServletRequestParameterException: Required String parameter 'service_id' is not present
2017-11-22T11:37:47.09+0100 [APP/PROC/WEB/0] OUT        at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:121) ~[spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
2017-11-22T11:37:47.09+0100 [APP/PROC/WEB/0] OUT        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
2017-11-22T11:37:47.09+0100 [APP/PROC/WEB/0] OUT        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
2017-11-22T11:37:47.09+0100 [APP/PROC/WEB/0] OUT        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
2017-11-22T11:37:47.09+0100 [APP/PROC/WEB/0] OUT        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
2017-11-22T11:37:47.09+0100 [APP/PROC/WEB/0] OUT        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.5.16.jar!/:8.5.16]
2017-11-22T11:37:47.09+0100 [APP/PROC/WEB/0] OUT        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-
```

I suspect this because the request mapping enters the branch with an expected cf instance id
https://github.com/spring-cloud/spring-cloud-cloudfoundry-service-broker/blob/7905d070c8f77c2638c5eb1d262f4bfafd66d83d/src/main/java/org/springframework/cloud/servicebroker/controller/ServiceInstanceController.java#L125-L131

It would be nice to be able to display a friendly error message such as "unexpected empty cfInstanceId"

I hope nevertheless this issue might help others running into this problem to fix their base broker url.

**Comment by scottfrederick** [comment]
@gberche-orange I can re-create this issue. I added a test for the empty instance ID condition (e.g. `https://mybroker.site.org//v2/service_instances/...` and tested it manually with a sample broker, and I always get an empty instance ID as expected. 

The `Required String parameter 'service_id' is not present` error would indicate that the request parameter `?service_id=aserviceid` was not parsed as expected, but I don't see how an empty instance ID at the front of the path would cause request parameters to be parsed incorrectly. 

Can you re-create this issue still? Is there a chance there was something wrong with the URL when you got that error?
